### ISSUE TITLE
Separate config option doesn't work

### ISSUE THREAD

**Issue by zoellner** [WilliamDASILVA/nuxt-robots-module#7]
I'm having trouble with the configuration being outside the modules array. 
I.e. what's in the readme under ` // With options` works, what's next after `or even` doesn't work - it ignores the options and uses the defaults. 
Latest version of everything. Using nuxt in universal mode, i.e. SSR

**Comment by WilliamDASILVA** [comment]
@zoellner Hello,

Thank you for reporting this issue.
I'll take a look at it very soon and will keep you updated. ❤️

**Comment by ricardogobbosouza** [comment]
@zoellner The documentation is wrong!
Use `robots` insetead of `'nuxt-robots-module'`
Fixed in #6

**Comment by WilliamDASILVA** [comment]
Hello there,

This has been fixed in the #6 PR by @ricardogobbosouza and released on the [v1.5.0 version](https://github.com/WilliamDASILVA/nuxt-robots-module/releases/tag/1.5.0).

Thank you for taking time to report this issue. ❤️
