### ISSUE TITLE
Host to correspondances

### ISSUE THREAD

**Issue by RomanNagornyi** [WilliamDASILVA/nuxt-robots-module#8]
Hello

Could you add Host directive to correspondences?

Thanks in advance.

**Comment by WilliamDASILVA** [comment]
Hello @RomanNagornyi,

This has been added in the #9 pull-request, released in the [v1.5.0 release](https://github.com/WilliamDASILVA/nuxt-robots-module/releases/tag/1.5.0).
Thank you for taking time to make this issue ❤️

**Comment by RomanNagornyi** [comment]
Hello @WilliamDASILVA 

Thanks for module ❤️
